
import type { Metadata } from 'next';
import './globals.css';
import CookieBanner from '../components/cookiebanner';
import GAWithConsent from '../components/GAWithConsent'; // <-- client component below

export const metadata: Metadata = {
  title: 'Aar00t',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="dark">
      <body>
        <CookieBanner />
        {/* Render children first, or wherever you prefer */}
        {children}

        {/* Mount GA only on the client when consent is granted */}
        <GAWithConsent />
      </body>
    </html>
  );
}
