
import type { Metadata } from 'next';
import './globals.css';
import CookieBanner from '../components/cookiebanner';
import GoogleConsent from '../components/google-consent';
import { GoogleAnalytics } from '@next/third-parties/google'

export const metadata: Metadata = {
  title: 'Aar00t',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="dark">
      <body>
        <CookieBanner />
        {/* Render children first, or wherever you prefer */}
        {children}
        <GoogleConsent />
      </body>
    </html>
  );
}
