import type { Metadata } from "next";
import "./globals.css";
import { GoogleAnalytics } from "@next/third-parties/google";
import CookieBanner from "../components/cookiebanner";


export const metadata: Metadata = {
  title: "Aar00t",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const gaId = process.env.NEXT_PUBLIC_GA_ID;

  const consent =
    typeof window !== "undefined" ? localStorage.getItem("cookie-consent") : null;

  return (
    <html lang="en" className="dark">
      <body>
        <CookieBanner />

        {children}

        {/* Load GA only if user granted consent */}
        {consent === "granted" && gaId && <GoogleAnalytics gaId={'G-RS0RCJV9BM'} />}
      </body>
    </html>
  );
}
